version: '3'
services:
  db:
    container_name: ediand_backend_mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    volumes:
      - ./containers_data/mysql:/var/lib/mysql

  web:
    container_name: ediand_backend_rails
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    command: >
      bash -c "rm -f tmp/pids/*.pid
      && bundle install --path vendor/bundle
      && bundle exec rails s -p 3000 -b 0.0.0.0"
    environment:
      RAILS_ENV: development
    volumes:
      - .:/ediand_backend:cached
    ports:
      - "3000:3000"
    links:
      - db
