version: 2.1

jobs:
  setup:
    working_directory: ~/ediant-backend
    docker:
      - image: circleci/python:3.8.0
    steps:
      - checkout
      - run:
          name: Install awscli
          command: sudo pip install awscli
  deploy:
    working_directory: ~/ediant-backend
    docker:
      - image: circleci/ruby:2.7.1
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "eb:b4:e5:c0:ba:6d:56:76:1f:06:97:25:e0:98:0d:cb"
      - restore_cache:
          keys:
            - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1-{{ arch }}-{{ .Branch }}
            - gem-cache-v1
      - run:
          name: Install gem
          command: |
            gem install bundler
            bundle install --path vendor/bundle --jobs=4
      - save_cache:
          key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Deploy application
          command: bash ./deploy.sh

workflows:
  all:
    jobs:
      - setup
      - deploy:
          requires:
            - setup
