version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.3.0

jobs:
  deploy:
    working_directory: ~/ediand-backend
    docker:
      - image: circleci/ruby:2.7.1
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "eb:b4:e5:c0:ba:6d:56:76:1f:06:97:25:e0:98:0d:cb"
      - restore_cache:
          keys:
            - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1-{{ arch }}-{{ .Branch }}
            - gem-cache-v1
      - run:
          name: Install gem
          command: |
            gem install bundler
            bundle install --path vendor/bundle --jobs=4
      - save_cache:
          key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Deploy application
          command: bash ~/ediand-backend/.circleci/deploy.sh

workflows:
  all:
    jobs:
      - deploy
