version: 2.1

jobs:
  deploy:
    working_directory: ~/ediand-backend
    docker:
      - image: circleci/ruby:2.7.1
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install python3-pip groff-base
      - run: sudo pip3 install awscli --ignore-installed six
      - run:
          name: Make ssh file
          command: |
            touch $HOME/.ssh/ediand_key_rsa
            cat ${EC2_KEY} > $HOME/.ssh/ediand_key_rsa
      - restore_cache:
          keys:
            - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1-{{ arch }}-{{ .Branch }}
            - gem-cache-v1
      - run:
          name: Install gem
          command: |
            gem install bundler
            bundle install --path vendor/bundle --jobs=4
      - save_cache:
          key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Deploy application
          command: bash ~/ediand-backend/.circleci/deploy.sh

workflows:
  all:
    jobs:
      - deploy
