version: 2.1

jobs:
  deploy:
    working_directory: ~/ediant-backend
    docker:
      - image: circleci/ruby:2.7.1
    steps:
      - checkout
      - run:
          name: Install gem
          command: |
            gem install bundler
            bundle install --path vendor/bundle --jobs=4

workflows:
  all:
    jobs:
      - deploy
